// Realistic mock data for healthcare platform

export const doctors = [
  {
    id: "1",
    name: "Dr. Sarah Chen",
    title: "MD, LCSW",
    specialty: "Anxiety & Depression",
    specialties: ["Anxiety", "Depression", "PTSD", "Life Transitions"],
    image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop&crop=face",
    rating: 4.9,
    reviewCount: 127,
    yearsExperience: 12,
    education: "Stanford University School of Medicine",
    languages: ["English", "Mandarin"],
    bio: "Dr. Chen specializes in evidence-based treatments for anxiety and depression. She uses a warm, collaborative approach to help patients develop practical coping strategies.",
    acceptsInsurance: ["Aetna", "Blue Cross Blue Shield", "Cigna", "United Healthcare"],
    sessionRate: 175,
    availability: ["Mon", "Tue", "Wed", "Thu"],
    nextAvailable: "Tomorrow at 2:00 PM",
  },
  {
    id: "2",
    name: "Dr. Marcus Williams",
    title: "PsyD",
    specialty: "Couples Therapy",
    specialties: ["Couples Therapy", "Marriage Counseling", "Communication", "Relationship Issues"],
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop&crop=face",
    rating: 4.8,
    reviewCount: 89,
    yearsExperience: 15,
    education: "Columbia University",
    languages: ["English", "Spanish"],
    bio: "Dr. Williams has helped hundreds of couples strengthen their relationships through evidence-based approaches including the Gottman Method and Emotionally Focused Therapy.",
    acceptsInsurance: ["Aetna", "Blue Cross Blue Shield", "Oscar Health"],
    sessionRate: 195,
    availability: ["Mon", "Wed", "Fri"],
    nextAvailable: "Jan 16 at 10:00 AM",
  },
  {
    id: "3",
    name: "Dr. Emily Rodriguez",
    title: "PhD, Licensed Psychologist",
    specialty: "Trauma & PTSD",
    specialties: ["Trauma", "PTSD", "Grief", "Complex Trauma"],
    image: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&h=400&fit=crop&crop=face",
    rating: 5.0,
    reviewCount: 64,
    yearsExperience: 8,
    education: "UCLA",
    languages: ["English", "Spanish", "Portuguese"],
    bio: "Dr. Rodriguez is trained in EMDR and other trauma-focused modalities. She creates a safe, supportive environment for healing.",
    acceptsInsurance: ["Cigna", "United Healthcare", "Kaiser Permanente"],
    sessionRate: 185,
    availability: ["Tue", "Thu", "Fri"],
    nextAvailable: "Jan 17 at 3:00 PM",
  },
  {
    id: "4",
    name: "Dr. James Park",
    title: "MD, Psychiatrist",
    specialty: "Medication Management",
    specialties: ["Medication Management", "ADHD", "Bipolar Disorder", "Schizophrenia"],
    image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&h=400&fit=crop&crop=face",
    rating: 4.7,
    reviewCount: 156,
    yearsExperience: 20,
    education: "Johns Hopkins School of Medicine",
    languages: ["English", "Korean"],
    bio: "Dr. Park takes a holistic approach to psychiatric care, combining medication management with lifestyle modifications for optimal mental wellness.",
    acceptsInsurance: ["Aetna", "Blue Cross Blue Shield", "Cigna", "United Healthcare", "Medicare"],
    sessionRate: 250,
    availability: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    nextAvailable: "Today at 4:30 PM",
  },
  {
    id: "5",
    name: "Dr. Amara Okonkwo",
    title: "LMFT",
    specialty: "Family Therapy",
    specialties: ["Family Therapy", "Adolescents", "Parenting", "Blended Families"],
    image: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400&h=400&fit=crop&crop=face",
    rating: 4.9,
    reviewCount: 98,
    yearsExperience: 10,
    education: "Northwestern University",
    languages: ["English", "Igbo"],
    bio: "Dr. Okonkwo specializes in helping families navigate transitions, improve communication, and build stronger connections.",
    acceptsInsurance: ["Blue Cross Blue Shield", "United Healthcare", "Oscar Health"],
    sessionRate: 165,
    availability: ["Mon", "Wed", "Thu", "Sat"],
    nextAvailable: "Jan 18 at 11:00 AM",
  },
];

export const insuranceProviders = [
  "Aetna",
  "Blue Cross Blue Shield",
  "Cigna",
  "United Healthcare",
  "Kaiser Permanente",
  "Oscar Health",
  "Medicare",
  "Medicaid",
  "Humana",
  "Anthem",
];

export const specialties = [
  "Anxiety",
  "Depression",
  "PTSD",
  "Trauma",
  "Couples Therapy",
  "Family Therapy",
  "ADHD",
  "Bipolar Disorder",
  "Grief",
  "Life Transitions",
  "Stress Management",
  "Self-Esteem",
  "Medication Management",
];

export const upcomingAppointments = [
  {
    id: "apt-1",
    doctorId: "1",
    doctorName: "Dr. Sarah Chen",
    doctorImage: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop&crop=face",
    specialty: "Anxiety & Depression",
    date: "January 15, 2026",
    time: "2:00 PM",
    type: "Video Session",
    status: "confirmed",
  },
  {
    id: "apt-2",
    doctorId: "4",
    doctorName: "Dr. James Park",
    doctorImage: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&h=400&fit=crop&crop=face",
    specialty: "Medication Management",
    date: "January 22, 2026",
    time: "10:30 AM",
    type: "Video Session",
    status: "confirmed",
  },
];

export const pastAppointments = [
  {
    id: "past-1",
    doctorId: "1",
    doctorName: "Dr. Sarah Chen",
    doctorImage: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop&crop=face",
    specialty: "Anxiety & Depression",
    date: "January 8, 2026",
    time: "2:00 PM",
    type: "Video Session",
    status: "completed",
    notes: "Discussed coping strategies for work anxiety. Patient showing improvement.",
    followUp: "Continue journaling exercises. Follow up in 1 week.",
  },
  {
    id: "past-2",
    doctorId: "1",
    doctorName: "Dr. Sarah Chen",
    doctorImage: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop&crop=face",
    specialty: "Anxiety & Depression",
    date: "January 1, 2026",
    time: "2:00 PM",
    type: "Video Session",
    status: "completed",
    notes: "Initial intake session. Established treatment goals.",
    followUp: "Begin CBT techniques. Schedule weekly sessions.",
  },
];

export const billingHistory = [
  {
    id: "inv-1",
    date: "January 8, 2026",
    service: "Therapy Session - Dr. Sarah Chen",
    duration: "50 min",
    total: 175,
    insuranceCovered: 140,
    patientOwes: 35,
    status: "paid",
    paymentDate: "January 8, 2026",
  },
  {
    id: "inv-2",
    date: "January 1, 2026",
    service: "Initial Consultation - Dr. Sarah Chen",
    duration: "60 min",
    total: 200,
    insuranceCovered: 160,
    patientOwes: 40,
    status: "paid",
    paymentDate: "January 1, 2026",
  },
];

export const messages = [
  {
    id: "msg-1",
    from: "Dr. Sarah Chen",
    fromImage: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop&crop=face",
    subject: "Session Notes from January 8th",
    preview: "Hi! I wanted to share the summary from our session and some resources...",
    date: "Jan 9, 2026",
    read: false,
  },
  {
    id: "msg-2",
    from: "CareConnect Support",
    fromImage: null,
    subject: "Welcome to CareConnect!",
    preview: "Thank you for joining CareConnect. Here's everything you need to get started...",
    date: "Dec 28, 2025",
    read: true,
  },
];

// Doctor dashboard mock data
export const doctorTodayAppointments = [
  {
    id: "doc-apt-1",
    patientName: "Alex Johnson",
    patientImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    time: "9:00 AM",
    duration: "50 min",
    type: "Follow-up Session",
    status: "completed",
  },
  {
    id: "doc-apt-2",
    patientName: "Maria Garcia",
    patientImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&crop=face",
    time: "10:30 AM",
    duration: "50 min",
    type: "Therapy Session",
    status: "in-progress",
  },
  {
    id: "doc-apt-3",
    patientName: "David Kim",
    patientImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face",
    time: "2:00 PM",
    duration: "50 min",
    type: "Initial Consultation",
    status: "upcoming",
  },
  {
    id: "doc-apt-4",
    patientName: "Sarah Thompson",
    patientImage: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face",
    time: "3:30 PM",
    duration: "50 min",
    type: "Follow-up Session",
    status: "upcoming",
  },
];

export const doctorEarnings = {
  thisWeek: 2450,
  thisMonth: 8750,
  pending: 1225,
  totalSessions: 42,
  avgPerSession: 175,
};

export const doctorPatients = [
  {
    id: "patient-1",
    name: "Alex Johnson",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    age: 32,
    startDate: "November 2025",
    lastSession: "January 14, 2026",
    totalSessions: 8,
    diagnosis: "Generalized Anxiety Disorder",
    status: "Active",
  },
  {
    id: "patient-2",
    name: "Maria Garcia",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&crop=face",
    age: 28,
    startDate: "December 2025",
    lastSession: "January 14, 2026",
    totalSessions: 5,
    diagnosis: "Major Depressive Disorder",
    status: "Active",
  },
  {
    id: "patient-3",
    name: "David Kim",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face",
    age: 45,
    startDate: "January 2026",
    lastSession: null,
    totalSessions: 0,
    diagnosis: "Pending Initial Assessment",
    status: "New",
  },
];

export const timeSlots = [
  "9:00 AM",
  "9:30 AM",
  "10:00 AM",
  "10:30 AM",
  "11:00 AM",
  "11:30 AM",
  "1:00 PM",
  "1:30 PM",
  "2:00 PM",
  "2:30 PM",
  "3:00 PM",
  "3:30 PM",
  "4:00 PM",
  "4:30 PM",
];

export const weekDays = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

// Provider onboarding data
export const credentialTypes = [
  { value: "md", label: "MD - Doctor of Medicine" },
  { value: "do", label: "DO - Doctor of Osteopathic Medicine" },
  { value: "psyd", label: "PsyD - Doctor of Psychology" },
  { value: "phd", label: "PhD - Doctor of Philosophy (Psychology)" },
  { value: "lcsw", label: "LCSW - Licensed Clinical Social Worker" },
  { value: "lmft", label: "LMFT - Licensed Marriage & Family Therapist" },
  { value: "lpc", label: "LPC - Licensed Professional Counselor" },
  { value: "lpcc", label: "LPCC - Licensed Professional Clinical Counselor" },
  { value: "np", label: "NP - Nurse Practitioner (Psychiatric)" },
  { value: "pa", label: "PA - Physician Assistant" },
];

export const licenseTypes = [
  { value: "medical", label: "Medical License (MD/DO)" },
  { value: "psychology", label: "Psychology License" },
  { value: "clinical_social_work", label: "Clinical Social Work License" },
  { value: "marriage_family", label: "Marriage & Family Therapy License" },
  { value: "professional_counseling", label: "Professional Counseling License" },
  { value: "nursing", label: "Advanced Practice Nursing License" },
];

export const usStates = [
  { value: "AL", label: "Alabama" },
  { value: "AK", label: "Alaska" },
  { value: "AZ", label: "Arizona" },
  { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" },
  { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" },
  { value: "DE", label: "Delaware" },
  { value: "FL", label: "Florida" },
  { value: "GA", label: "Georgia" },
  { value: "HI", label: "Hawaii" },
  { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" },
  { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" },
  { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" },
  { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" },
  { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" },
  { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" },
  { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" },
  { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" },
  { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" },
  { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" },
  { value: "ND", label: "North Dakota" },
  { value: "OH", label: "Ohio" },
  { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" },
  { value: "PA", label: "Pennsylvania" },
  { value: "RI", label: "Rhode Island" },
  { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" },
  { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" },
  { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" },
  { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" },
  { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" },
  { value: "WY", label: "Wyoming" },
  { value: "DC", label: "District of Columbia" },
];
